language: python
python:
  - "2.7"

env:
  global:
    - GH_REF: github.com/CodeIgniter-Chinese/codeigniter4-user-guide.git
    - secure: "Lg6Hm+QklAHGlQ68qNIXhlz1LY7+easm8sv8rrY7Y52ZHU1l04iQnrNl/d+crk/OJRIoqz/pVqS37fCO94IeAif/Zd3/sEj3UM4imDfGqSfLYu20Hd+aS/n3KhioHULv24ZSzzaHa3BCfKCRXpH7kO5elkqyOaD9j0VVstAjKEmcazOm33s4YWbQOIMbGUgk4GxqqsWOoSo3GCnaSqXaI9T3Mv8hsGT8KUjWuZqXRrbKlw7lytYv1r8xTYbGNkfn0R0LW3iCNSDzNtS/vzvYiWsGO4jOssaCHy6Fa1vJyR/G2+SH/B8Lhf3mm5h9Bc53569TkubA32oj9d6PE09WR5v1z8mnpYUbwT44NFe/nAkXvcJgAP6FvHV/e3c/CtKA19iw+FBbeoTwtSB5qzCHiXrrpLYABq2MfNA7ysg6J8NAT2WZPv3Z/mg7FR8m21UqNhQEeaHBQea7e95QAj4gsrYBn5BXPGlOcw6jen3OqvxgZUfNPHgT3iEZ1PjRJRy0l0X9i+gYUgcSkZRj/cdyZdcz0FUPo9T+NqNzdvn/58/zalYdBxXTffCj0mGM/x+EDMupLhcvdSWqu9VawNh9OmJ821+BwbI72rQMI2AA4gd3YkIFpadLeAo2Phoz7fwWSM++udnRtxjFTeJJZncHe4majijMgxEHNU5xxicu5cQ="

cache:
  directories:
  - $HOME/.cache/pip

sudo: false

addons:
  apt:
    packages:
    - texlive-xetex
    - texlive-latex-recommended
    - texlive-fonts-recommended
    - texlive-latex-extra
    - lmodern

install:
  - pip install --upgrade pip
  - pip install "sphinx==1.4.5"
  - pip install sphinxcontrib-phpdomain
  - pip install jieba
  - cd cilexer && python setup.py install && cd ..

script:
  - make html
#  - wget http://codeigniter-chinese.github.io/codeigniter-user-guide/_fonts/fonts.tar.gz
#  - mkdir $HOME/.fonts && tar xzf fonts.tar.gz && cp *.ttf $HOME/.fonts/
#  - make latexpdf

after_success:
  - bash ./deploy-gh-pages.sh

# Flags used here, not in `make html`:
#  -n   Run in nit-picky mode. Currently, this generates warnings for all missing references.
#  -W   Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1.

git:
  depth: 10

branches:
  only:
    - master
